import time
import pyautogui
time.sleep(5)

pyautogui.press('enter')
pyautogui.write('162')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('248')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('270')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('293')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('203')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('203')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('270')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('293')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('198')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('248')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('293')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('162')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('216')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('293')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')