import re
import time
import pyautogui
time.sleep(3)

pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('261')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('243')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('243')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('225')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('243')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('243')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('234')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('234')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('234')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('234')
pyautogui.press('enter')
pyautogui.press('down')