import time
import pyautogui
time.sleep(5)

pyautogui.press('enter')
pyautogui.write('162')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('300')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('360')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('450')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('495')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('270')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('300')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('360')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('300')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('300')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('338')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('288')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('338')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('338')
pyautogui.press('enter')
pyautogui.press('down')

pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')

pyautogui.press('enter')
pyautogui.write('300')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('300')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('315')
pyautogui.press('enter')
pyautogui.press('down')
pyautogui.press('enter')
pyautogui.write('338')
pyautogui.press('enter')
pyautogui.press('down')




