import re
import tkinter as tk
from tkinter import simpledialog

# Your existing exclusion and replacement patterns
exclude_patterns = [
    re.compile(r'^\s*\+'),
    re.compile(r'^\s*-\s*'),
    re.compile(r'^\s*YES'),
    re.compile(r'^\s*1st Touchdown Scorer / 2nd Touchdown Scorer'),
    re.compile(r'^\s*1st Touchdown Scorer / Moneyline'),
    re.compile(r'^\s*1ST TOUCHDOWN SCORER / MONEYLINE'),
    re.compile(r'^\s*ANYTIME AWAY TOUCHDOWN SCORER / MONEYLINE'),
    re.compile(r'^\s*ANYTIME HOME TOUCHDOWN SCORER / MONEYLINE'),
    re.compile(r'^\s*BOOSTED ODDS'),
    re.compile(r'^\s*SPECIALS'),
    re.compile(r'^\s*BOOSTED WIN PARLAY'),
    re.compile(r'^\s*ODDS BOOST - BOOSTED WIN PARLAY'),
    re.compile(r'^\s*ODDS BOOST - ODDS BOOST'),
    re.compile(r'^\s*ODDS BOOST'),
    re.compile(r'^\s*BET BUILDER'),
    re.compile(r'^\s*GAME SPECIALS: FEATURED'),
    re.compile(r'^\s*GAME SPECIALS: UP TO \+450'),
    re.compile(r'^\s*GAME SPECIALS: \+500 TO \+1900'),
    re.compile(r'^\s*GAME SPECIALS: \+2000 TO \+4900'),
    re.compile(r'^\s*GAME SPECIALS: \+5000 OR ABOVE'),
    re.compile(r'^\s*WINNER'),
    re.compile(r'^\s*REGULAR TIME ONLY'),
    re.compile(r'^\s*SHOW LESS'),
    re.compile(r'^\s*#BETYOURWAY - TEAM FOCUS'),
    re.compile(r'^\s*#BETYOURWAY UP TO 10.0'),
    re.compile(r'^\s*#BETYOURWAY UP TO 26.0'),
    re.compile(r'^\s*PARLAYS: ODDS < \+1000'),
    re.compile(r'^\s*PARLAYS: ODDS > \+5000'),
    re.compile(r'^\s*PARLAYS: ODDS \+\d+ TO \+\d+'),
    re.compile(r'^\s*PERFORMANCE DOUBLES'),
    re.compile(r'^\s*REQUESTED SPECIALS'),
    re.compile(r'^\s*REGULAR TIME ONLY. BETS SETTLED USING OPTA DATA. THE PLAYERS MUST START THE MATCH FOR BETS TO STAND.'),
    re.compile(r'^\s*BETS SETTLED USING OPTA DATA. THE PLAYER MUST START THE MATCH FOR BETS TO STAND.'),
    re.compile(r'^\s*BETS SETTLED USING OPTA DATA. THE PLAYERS MUST START THE MATCH FOR BETS TO STAND.'),
    re.compile(r'^\s*THE PLAYER MUST START THE MATCH FOR BETS TO STAND'),
    re.compile(r'^\s*THE PLAYERS MUST START THE MATCH FOR BETS TO STAND'),
    re.compile(r'^\s*PASS TDS WILL BE CREDITED TO THE RECEIVER NOT THE PASSER FOR WAGERING PURPOSES. OTHERS ON REQUEST.'),
    # Add more patterns here
]

replace_patterns = [
    # Add more REGULAR EXPRESSIONS patterns here
    (re.compile(r'\b , \b'), ','),
    (re.compile(r'\b / \b'), '/'),
    (re.compile(r'\b AND \b'), '/'),
    (re.compile(r'\b, \b'), ','),
    (re.compile(r'\bSHOTS ON GOAL\b'), 'SOT'),
    (re.compile(r'\bTO HAVE \b'), ''),
    (re.compile(r'\bTO WIN\b'), 'WINS'),
    (re.compile(r'\b\ & \b'), '/'),
    (re.compile(r'\bOFFENSIVE TOUCHDOWN\b'), 'OFF TD'),
    (re.compile(r'\bFIELD GOAL ATTEMPT\b'), 'FG ATT'),
    (re.compile(r'\b\+ \b'), '+'),
    (re.compile(r'\bTHE FIRST TD\b'), '1ST TD'),
    (re.compile(r'\bTHE SECOND TD\b'), '2ND TD'),
    (re.compile(r'\bTHE LAST TD\b'), 'LAST TD'),
    # Add more TEAMS replacement patterns here
    (re.compile(r'\bARI CARDINALS\b'), 'CARDINALS'),
    (re.compile(r'\bARIZONA CARDINALS\b'), 'CARDINALS'),
    (re.compile(r'\bBALTIMORE RAVENS\b'), 'RAVENS'),
    (re.compile(r'\bBUFFALO BILLS\b'), 'BILLS'),
    (re.compile(r'\bCAR PANTHERS\b'), 'PANTHERS'),
    (re.compile(r'\bKANSAS CITY CHIEFS\b'), 'CHIEFS'),
    (re.compile(r'\bHOUSTON TEXANS\b'), 'TEXANS'),
    (re.compile(r'\bMIN VIKINGS\b'), 'VIKINGS'),
    (re.compile(r'\bPHI EAGLES\b'), 'EAGLES'),
    (re.compile(r'\bSEA SEAHAWKS\b'), 'SEAHAWKS'),
    (re.compile(r'\bDEN BRONCOS\b'), 'BRONCOS'),
    (re.compile(r'\bDETROIT LIONS\b'), 'LIONS'),
    (re.compile(r'\bTB BUCCANEERS\b'), 'BUCCANEERS'),
    (re.compile(r'\bTAMPA BAY BUCCANEERS\b'), 'BUCCANEERS'),
    (re.compile(r'\bNY GIANTS\b'), 'GIANTS'),
    (re.compile(r'\bSF 49ERS\b'), '49ERS'),
    (re.compile(r'\bSAN FRANCISCO 49ERS\b'), '49ERS'),
    (re.compile(r'\bTEN TITANS\b'), 'TITANS'),

    (re.compile(r'\bWAS COMMANDERS\b'), 'COMMANDERS'),
    (re.compile(r'\bLOS ANGELES CHARGERS\b'), 'LA CHARGERS'),
    (re.compile(r'\bLAS VEGAS RAIDERS\b'), 'LV RAIDERS'),
    (re.compile(r'\bWASHINGTON COMMANDERS\b'), 'COMMANDERS'),
    # Add more BASKETBALL patterns here
    (re.compile(r'\bREBOUNDS\b'), 'RBDS'),
    (re.compile(r'\bTHREE POINT FIELD GOALS\b'), '3PT FG MADE'),
    (re.compile(r'\bASSISTS\b'), 'ASSTS'),
    (re.compile(r'\bPOINTS\b'), 'PTS'),
    (re.compile(r'\bTOTAL\b'), 'TOT'),
    # Add more BASEBALL replacement patterns here
    (re.compile(r'\bTOUCHDOWNS\b'), 'TDS'),
    (re.compile(r'\bFIELD GOAL ATTEMPT\b'), 'FG ATTEMPT'),
    (re.compile(r'\bA TOUCHDOWN\b'), 'A TD'),
    (re.compile(r'\bHOME RUNS\b'), 'HRS'),
    (re.compile(r'\bSTRIKEOUTS \b'), 'SO'),
    (re.compile(r'\bSTRIKEOUTS/\b'), 'SO/'),
    # Add more SOCCER patterns here
    # Add more FOOTBALL patterns here
    (re.compile(r'\b1ST QUARTER\b'), '1Q'),
    (re.compile(r'\bANYTIME TOUCHDOWN EACH\b'), 'TD EACH'),
    (re.compile(r'\bIN BOTH CHAMPIONSHIP SUNDAY GAMES\b'), '(2 SUNDAY GAMES)'),
    (re.compile(r'\b PASSING YARDS\b'), 'PASS YDS'),
    (re.compile(r'\b RECEIVING YARDS\b'), 'RCV YDS'),
    (re.compile(r'\b RUSHING YARDS\b'), 'RUSH YDS'),
    (re.compile(r'\bANYTIME TOUCHDOWN EACH\b'), 'TD EACH'),
    (re.compile(r'\bTO EACH INDIVIDUALLY SCORE\b'), 'EACH'),
    (re.compile(r'\bCARRIES\b'), 'CAR'),
    (re.compile(r'\bCOMPLETIONS\b'), 'CMPTS'),
    (re.compile(r'\bPASSING TDS\b'), 'PASS TDS'),
    (re.compile(r'\bPASSING TOUCHDOWNS\b'), 'PASS TDS'),
    (re.compile(r'\bPASSING YARDS\b'), 'PASS YDS'),
    (re.compile(r'\bPASSING YDS\b'), 'PASS YDS'),
    (re.compile(r'\bPASSING\b'), 'PASS'),
    (re.compile(r'\bRECEIVING YARDS\b'), 'RCV YDS'),
    (re.compile(r'\bRECEPTIONS\b'), 'RCPTS'),
    (re.compile(r'\bRUSHING YARDS\b'), 'RUSH YDS'),
    (re.compile(r'\bRUSHING YDS\b'), 'RUSH YDS'),
    (re.compile(r'\bRUSHING\b'), 'RUSH'),
    (re.compile(r'\bTOUCHDOWNS\b'), 'TDS'),
    (re.compile(r'\bYARDS\b'), 'YDS'),
    # Add more PLAYER NAMES patterns here
    (re.compile(r'\bAARON JONES\b'), 'A.JONES'),
    (re.compile(r'\bAARON RODGERS\b'), 'A.RODGERS'),
    (re.compile(r'\bALBERT OKWUEGBUNAM\b'), 'A.OKWUEGBUNAM'),
    (re.compile(r'\bALEXANDER MATTISON\b'), 'A.MATTISON'),
    (re.compile(r'\bALLEN ROBINSON\b'), 'A.ROBINSON'),
    (re.compile(r'\bALVIN KAMARA\b'), 'A.KAMARA'),
    (re.compile(r'\bANDREA BELOTTI\b'), 'A.BELOTTI'),
    (re.compile(r'\bANTHONY MCFARLAND\b'), 'A.MCFARLAND'),
    (re.compile(r'\bAUSTIN EKELER\b'), 'A.EKELER'),
    (re.compile(r'\bBAKER MAYFIELD\b'), 'B.MAYFIELD'),
    (re.compile(r'\bBEAUX COLLINS\b'), 'B.COLLINS'),
    (re.compile(r'\bBO NIX\b'), 'B.NIX'),
    (re.compile(r'\bBREECE HALL\b'), 'B.HALL'),
    (re.compile(r'\bBRIAN ROBINSON\b'), 'B.ROBINSON'),
    (re.compile(r'\bBROCK PURDY\b'), 'B.PURDY'),
    (re.compile(r'\bBUCKY IRVING\b'), 'B.IRVING'),
    (re.compile(r'\bCADE KLUBNIK\b'), 'C.KLUBNIK'),
    (re.compile(r'\bCALVIN AUSTIN\b'), 'C.AUSTIN'),
    (re.compile(r'\bCEEDEE LAMB\b'), 'C.LAMB'),
    (re.compile(r'\bCHRIS RODRIGUEZ\b'), 'C.RODRIGUEZ'),
    (re.compile(r'\bCHRISTIAN MCCAFFREY\b'), 'C.MCCAFFREY'),
    (re.compile(r'\bCLYDE EDWARDS-HELAIRE\b'), 'C.EDWARDS-HELAIRE'),
    (re.compile(r'\bCOLBY PARKINSON\b'), 'C.PARKINSON'),
    (re.compile(r'\bCOOPER KUPP\b'), 'C.KUPP'),
    (re.compile(r'\bCORDARRELLE PATTERSON\b'), 'C.PATTERSON'),
    (re.compile(r'\bDANIEL BELLINGER\b'), 'D.BELLINGER'),
    (re.compile(r'\bDARNELL WASHINGTON\b'), 'D.WASHINGTON'),
    (re.compile(r'\bDEMARIO DOUGLAS\b'), 'D.DOUGLAS'),
    (re.compile(r'\bDEONTE HARTY\b'), 'D.HARTY'),
    (re.compile(r'\bDEREK CARR\b'), 'D.CARR'),
    (re.compile(r'\bDEVEN THOMPKINS\b'), 'D.THOMPKINS'),
    (re.compile(r'\bDEVIN SINGLETARY\b'), 'D.SINGLETARY'),
    (re.compile(r'\bDEVIN DUVERNAY\b'), 'D.DUVERNAY'),
    (re.compile(r'\bDEEBO SAMUEL\b'), 'D.SAMUEL'),
    (re.compile(r'\bDONALD PARHAM\b'), 'D.PARHAM'),
    (re.compile(r'\bDONOVAN PEOPLES-JONES\b'), 'D.PEOPLES-JONES'),
    (re.compile(r'\bDONTAYVION WICKS\b'), 'D.WICKS'),
    (re.compile(r'\bDYLAN EDWARDS\b'), 'D.EDWARDS'),
    (re.compile(r'\bEQUANIMEOUS ST. BROWN\b'), 'E.ST. BROWN'),
    (re.compile(r'\bFOSTER MOREAU\b'), 'F.MOREAU'),
    (re.compile(r'\bGEORGE KITTLE\b'), 'G.KITTLE'),
    (re.compile(r'\bGODWIN IGWEBUIKE\b'), 'G.IGWEBUIKE'),
    (re.compile(r'\bGRANT CALCATERRA\b'), 'G.CALCATERRA'),

    (re.compile(r'\bGUNNER OLSZEWSKI\b'), 'G.OLSZEWSKI'),
    (re.compile(r'\bHARRISON WALLACE\b'), 'H.WALLACE'),
    (re.compile(r'\bIHMIR SMITH-MARSETTE\b'), 'I.SMITH-MARSETTE'),
    (re.compile(r'\bISIAH PACHECO\b'), 'I.PACHECO'),
    (re.compile(r'\bJAHMYR GIBBS\b'), 'J.GIBBS'),
    (re.compile(r'\bJAKE FERGUSON\b'), 'J.FERGUSON'),
    (re.compile(r'\bJALEEL MCLAUGHLIN\b'), 'J.MCLAUGHLIN'),
    (re.compile(r'\bJALEN HURTS\b'), 'J.HURTS'),
    (re.compile(r'\bJALEN MCMILLAN\b'), 'J.MCMILLAN'),
    (re.compile(r'\bJALEN MILROE\b'), 'J.MILROE'),
    (re.compile(r'\bJAMAAL WILLIAMS\b'), 'J.WILLIAMS'),
    (re.compile(r'\bJARED GOFF\b'), 'J.GOFF'),
    (re.compile(r'\bJASE MCCLELLAN\b'), 'J.MCCLELLAN'),
    (re.compile(r'\bJAVONTE WILLIAMS\b'), 'J.WILLIAMS'),
    (re.compile(r'\bJAXSON DART\b'), 'J.DART'),
    (re.compile(r'\bJERMAINE BURTON\b'), 'J.BURTON'),
    (re.compile(r'\bJIMMY GAROPPOLO\b'), 'J.GAROPPOLO'),
    (re.compile(r'\bJOHNNY WILSON\b'), 'J.WILSON'),
    (re.compile(r'\bJORDAN LOVE\b'), 'J.LOVE'),
    (re.compile(r'\bJORDAN TRAVIS\b'), 'J.TRAVIS'),
    (re.compile(r'\bJOSHUA PALMER\b'), 'J.PALMER'),
    (re.compile(r'\bJUJU SMITH-SCHUSTER\b'), 'J.SMITH-SCHUSTER'),
    (re.compile(r'\bJUSTIN FIELDS\b'), 'J.FIELDS'),
    (re.compile(r'\bJUSTIN HERBERT\b'), 'J.HERBERT'),
    (re.compile(r'\bJUSTIN JEFFERSON\b'), 'J.JEFFERSON'),
    (re.compile(r'\bKAYTRON ALLEN\b'), 'K.ALLEN'),
    (re.compile(r'\bKEANDRE LAMBERT-SMITH\b'), 'K.LAMBERT-SMITH'),
    (re.compile(r'\bKEENAN ALLEN\b'), 'K.ALLEN'),
    (re.compile(r'\bKENNETH GAINWELL\b'), 'K.GAINWELL'),
    (re.compile(r'\bKENNETH WALKER III\b'), 'K.WALKER III'),
    (re.compile(r'\bKEON COLEMAN\b'), 'K.COLEMAN'),
    (re.compile(r'\bKHALIL HERBERT\b'), 'K.HERBERT'),
    (re.compile(r'\bKHVICHA KVARATSKHELIA\b'), 'K.KVARATSKHELIA '),
    (re.compile(r'\bKIRK COUSINS\b'), 'K.COUSINS'),
    (re.compile(r'\bKRISTIAN WILKERSON\b'), 'K.WILKERSON'),
    (re.compile(r'\bKYLE PITTS\b'), 'K.PITTS'),
    (re.compile(r'\bKYLEN GRANSON\b'), 'K.GRANSON'),
    (re.compile(r'\bKYREN WILLIAMS\b'), 'K.WILLIAMS'),
    (re.compile(r'\bLAMAR JACKSON\b'), 'L.JACKSON'),
    (re.compile(r'\bLAVISKA SHENAULT JR\b'), 'L.SHENAULT JR'),
    (re.compile(r'\bLAVISKA SHENAULT\b'), 'L.SHENAULT'),
    (re.compile(r'\bLESHON WILLIAMS\b'), 'L.WILLIAMS'),
    (re.compile(r'\bMAC JONES\b'), 'M.JONES'),
    (re.compile(r'\bMACK HOLLINS\b'), 'M.HOLLINS'),
    (re.compile(r'\bMARQUEZ VALDES-SCANTLING\b'), 'M.VALDES-SCANTLING'),
    (re.compile(r'\bMATTHEW STAFFORD\b'), 'M.STAFFORD'),
    (re.compile(r'\bMICHAEL PITTMAN\b'), 'M.PITTMAN'),
    (re.compile(r'\bMICHAEL THOMAS\b'), 'M.THOMAS'),
    (re.compile(r'\bMONTRELL WASHINGTON\b'), 'M.WASHINGTON'),
    (re.compile(r'\bNICHOLAS SINGLETON\b'), 'N.SINGLETON'),
    (re.compile(r'\bNELSON AGHOLOR\b'), 'N.AGHOLOR'),
    (re.compile(r'\bNICK WESTBROOK-IKHINE\b'), 'N.WESTBROOK-IKHINE'),
    (re.compile(r'\bNICK WESTBROOK-IKHINE\b'), 'WESTBROOK-IKHINE'),
    (re.compile(r'\bNICO COLLINS\b'), 'N.COLLINS'),
    (re.compile(r'\bNICO RAGAINI\b'), 'N.RAGAINI'),
    (re.compile(r'\bODELL BECKHAM JR\b'), 'O.BECKHAM JR'),
    (re.compile(r'\bOLAMIDE ZACCHEAUS\b'), 'O.ZACCHEAUS'),
    (re.compile(r'\bPARKER WASHINGTON\b'), 'P.WASHINGTON'),
    (re.compile(r'\bPATRICK MAHOMES\b'), 'P.MAHOMES'),
    (re.compile(r'\bPATRICK RICARD\b'), 'P.RICARD'),
    (re.compile(r'\bPEYTON HENDERSHOT\b'), 'P.HENDERSHOT'),
    (re.compile(r'\bRAHEEM BLACKSHEAR\b'), 'R.BLACKSHEAR'),
    (re.compile(r'\bRASHOD BATEMAN\b'), 'R.BATEMAN'),
    (re.compile(r'\bRASHEE RICE\b'), 'R.RICE'),
    (re.compile(r'\bRHAMONDRE STEVENSON\b'), 'R.STEVENSON'),
    (re.compile(r'\bROME ODUNZE\b'), 'R.ODUNZE'),
    (re.compile(r'\bRYAN TANNEHILL\b'), 'R.TANNEHILL'),
    (re.compile(r'\bSHEDEUR SANDERS\b'), 'S.SANDERS'),
    (re.compile(r'\bSTEPHAN EL SHAARAWY\b'), 'S.EL SHAARAWY'),
    (re.compile(r'\bSTERLING SHEPARD\b'), 'S.SHEPARD'),
    (re.compile(r'\bTERRACE MARSHALL JR\b'), 'T.MARSHALL JR'),
    (re.compile(r'\bTERRY MCLAURIN\b'), 'T.MCLAURIN'),
    (re.compile(r'\bTEZ JOHNSON\b'), 'T.JOHNSON'),
    (re.compile(r'\bTONY POLLARD\b'), 'T.POLLARD'),
    (re.compile(r'\bTRAVIS ETIENNE\b'), 'T.ETIENNE'),
    (re.compile(r'\bTRAVIS KELCE\b'), 'T.KELCE'),
    (re.compile(r'\bTRAYVEON WILLIAMS\b'), 'T.WILLIAMS'),
    (re.compile(r'\bTREY BENSON\b'), 'T.BENSON'),
    (re.compile(r'\bTROY FRANKLIN\b'), 'T.FRANKLIN'),
    (re.compile(r'\bTUA TAGOVAILOA\b'), 'T.TAGOVAILOA'),
    (re.compile(r'\bTYLER WARREN\b'), 'T.WARREN'),
    (re.compile(r'\bTYRION DAVIS-PRICE\b'), 'T.DAVIS-PRICE'),
    (re.compile(r'\bVICTOR OSIMHEN\b'), 'V.OSIMHEN'),
    (re.compile(r'\bVINICIUS JUNIOR\b'), 'V.JUNIOR'),
    (re.compile(r'\bWILL SHIPLEY\b'), 'W.SHIPLEY'),
    (re.compile(r'\bXAVIER WEAVER\b'), 'X.WEAVER'),
    (re.compile(r'\bZAY FLOWERS\b'), 'Z.FLOWERS'),

    # Add more REGULAR EXPRESSIONS patterns here
    (re.compile(r'\b -\b'), '-'),
    (re.compile(r'\b \(WAS\)\b'), '(WAS)'),
    (re.compile(r'\b \(\b'), '('),
    (re.compile(r'\b\)\s{2},\b'), '),'),
    (re.compile(r'\bTO COMBINE FOR \b'), 'COMBINED'),
    (re.compile(r'\bTO SCORE THE 1ST TOUCHDOWN OF THE MATCH\b'), 'SCORE 1ST TD IN GAME'),
    (re.compile(r'\bTO SCORE\b'), 'SCORE'),
    (re.compile(r'\b\) \& \b'), '),'),
    (re.compile(r'\b\) \, \b'), '),'),
    (re.compile(r'\b ,\b'), ','),
    # Add more TEAMS replacement patterns here
    (re.compile(r'\bSTATE\b'), 'ST'),
    (re.compile(r'\bMIAMI DOLPHINS\b'), 'DOLPHINS'),
    (re.compile(r'\bNEW YORK GIANTS\b'), 'GIANTS'),
    (re.compile(r'\bPHILADELPHIA EAGLES\b'), 'EAGLES'),
    (re.compile(r'\bATLANTA DREAM\b'), 'ATL DREAM'),
    (re.compile(r'\bDALLAS WINGS\b'), 'DAL WINGS'),
    (re.compile(r'\bNEW YORK LIBERTY\b'), 'NY LIBERTY'),
    (re.compile(r'\bWASHINGTON MYSTICS\b'), 'WAS MYSTICS'),
    # Add more BASKETBALL patterns here
    (re.compile(r'\bTOTAL POINTS OVER\b'), 'TOT PTS OV'),
    (re.compile(r'\bTOTAL POINTS UNDER\b'), 'TOT PTS UND'),
    # Add more BASEBALL replacement patterns here
    (re.compile(r'\bSTRIKEOUTS\b'), 'SO'),
    # Add more SOCCER patterns here
    (re.compile(r'\b1ST QUARTER\b'), '1Q'),
    (re.compile(r'\bREC\. YARDS\b'), 'RCV YDS'),
    (re.compile(r'\bRUSH TOUCHDOWN\b'), 'RUSH TDS'),
    # Add more PLAYER NAMES patterns here
    (re.compile(r'\bAMON-RA ST\. BROWN\b'), 'A ST.BROWN'),
    (re.compile(r'\bADRIAN HOUSER\b'), 'A.HOUSER'),
    (re.compile(r'\bAARON JUDGE\b'), 'A.JUDGE'),
    (re.compile(r'\bAARON NOLA\b'), 'A.NOLA'),
    (re.compile(r'\bANTHONY RICHARDSON\b'), 'A.RICHARDSON'),
    (re.compile(r'\bALLISHA GRAY\b'), 'A.GRAY'),
    (re.compile(r'\bALVARO MORATA\b'), 'A.MORATA'),
    (re.compile(r'\bARIKE OGUNBOWALE\b'), 'A.OGUNBOWALE'),
    (re.compile(r'\bAUSTIN RILEY\b'), 'A.RILEY'),
    (re.compile(r'\bBIJAN ROBINSON\b'), 'B.ROBINSON'),
    (re.compile(r'\bBRANDON AIYUK\b'), 'B.AIYUK'),
    (re.compile(r'\bBRANDON PFAADT\b'), 'B.PFAADT'),
    (re.compile(r'\bBRAXTON GARRETT\b'), 'B.GARRETT'),
    (re.compile(r'\bBRYCE ELDER\b'), 'B.ELDER'),
    (re.compile(r'\bBRYCE HARPER\b'), 'B.HARPER'),
    (re.compile(r'\bCARLOS SANTANA\b'), 'C.SANTANA'),
    (re.compile(r'\bCHEYENNE PARKER\b'), 'C.PARKER'),
    (re.compile(r'\bCHRIS GODWIN\b'), 'C.GODWIN'),
    (re.compile(r'\bCHRIS OLAVE\b'), 'C.OLAVE'),
    (re.compile(r'\bCHRISTIAN KIRK\b'), 'C.KIRK'),
    (re.compile(r'\bCHRISTIAN WALKER\b'), 'C.WALKER'),
    (re.compile(r'\bCHRISTIAN WATSON\b'), 'C.WATSON'),
    (re.compile(r'\bCIRO IMMOBILE\b'), 'C.IMMOBILE'),
    (re.compile(r'\bCALVIN RIDLEY\b'), 'C.RIDLEY'),
    (re.compile(r'\bCOOPER LEGAS \b'), 'C.LEGAS '),
    (re.compile(r'\bCORBIN CARROLL\b'), 'C.CARROLL'),
    (re.compile(r'\bCOREY SEAGER\b'), 'C.SEAGER'),
    (re.compile(r'\bCOURTLAND SUTTON\b'), 'C.SUTTON'),
    (re.compile(r'\bCRISTIAN JAVIER\b'), 'C.JAVIER'),
    (re.compile(r'\bDAVID MONTGOMERY\b'), 'D.MONTGOMERY'),
    (re.compile(r'\bDAK PRESCOTT\b'), 'D.PRESCOTT'),
    (re.compile(r'\bDAVANTE ADAMS\b'), 'D.ADAMS'),
    (re.compile(r'\bPAULO DYBALA\b'), 'P.DYBALA'),
    (re.compile(r'\bABOU OUATTARA\b'), 'A.OUATTARA'),
    (re.compile(r'\bSTEVEN BERGWIJN\b'), 'S.BERGWIJN'),
    (re.compile(r'\bBRIAN BROBBEY\b'), 'B.BROBBEY'),
    (re.compile(r'\bAMINE HARIT\b'), 'A.HARIT'),
    (re.compile(r'\bDANIEL JONES\b'), 'D.JONES'),
    (re.compile(r'\bDAULTON VARSHO\b'), 'D.VARSHO'),
    (re.compile(r'\bDARIUS SLAYTON\b'), 'D.SLAYTON'),
    (re.compile(r'\bDEANDRE HOPKINS\b'), 'D.HOPKINS'),
    (re.compile(r'\bDENIS BOUANGA\b'), 'D.BOUANGA'),
    (re.compile(r'\bDESHAUN WATSON\b'), 'D.WATSON'),
    (re.compile(r'\bDESMOND RIDDER\b'), 'D.RIDDER'),
    (re.compile(r'\bDEVONTA SMITH\b'), 'D.SMITH'),
    (re.compile(r'\bDRAKE LONDON\b'), 'D.LONDON'),
    (re.compile(r'\bEMMANUEL MICHEL\b'), 'E.MICHEL'),
    (re.compile(r'\bELENA DELLE DONNE\b'), 'E.DONNE'),
    (re.compile(r'\bELIJAH MOORE\b'), 'E.MOORE'),
    (re.compile(r'\bFREDDY PERALTA\b'), 'F.PERALTA'),
    (re.compile(r'\bGARRETT WILSON\b'), 'G.WILSON'),
    (re.compile(r'\bGENO SMITH\b'), 'G.SMITH'),
    (re.compile(r'\bGLEYBER TORRES\b'), 'G.TORRES'),
    (re.compile(r'\bHAASON REDDICK\b'), 'H.REDDICK'),
    (re.compile(r'\bJAKOBI MEYERS\b'), 'J.MEYERS'),
    (re.compile(r'\bJA\'MARR CHASE\b'), 'J.CHASE'),
    (re.compile(r'\bJESHAUN JONES\b'), 'J.JONES'),
    (re.compile(r'\bJOE BURROW\b'), 'J.BURROW'),
    (re.compile(r'\bJOHN LEE ELDRIDGE III\b'), 'J.ELDRIDGE III'),
    (re.compile(r'\bJORGE POLANCO\b'), 'J.POLANCO'),
    (re.compile(r'\bJOSE URQUIDY\b'), 'J.URQUIDY'),
    (re.compile(r'\bJOSH DONALDSON\b'), 'J.DONALDSON'),
    (re.compile(r'\bJUJU SMITH-SCHUSTER\b'), 'SMITH-SCHUSTER'),
    (re.compile(r'\bKADEN PRATHER\b'), 'K.PRATHER'),
    (re.compile(r'\bKENDRE MILLER\b'), 'K.MILLER'),
    (re.compile(r'\bKENNY PICKETT\b'), 'K.PICKETT'),
    (re.compile(r'\bKEVIN GAUSMAN\b'), 'K.GAUSMAN'),
    (re.compile(r'\bKYLE SCHWARBER\b'), 'K.SCHWARBER'),
    (re.compile(r'\bKYLIAN MBAPPE\b'), 'K.MBAPPE'),
    (re.compile(r'\bLANCE LYNN\b'), 'L.LYNN'),
    (re.compile(r'\bLEONARDO CAMPANA\b'), 'L.CAMPANA'),
    (re.compile(r'\bLORENZO INSIGNE\b'), 'L.INSIGNE'),
    (re.compile(r'\bMALACHI FIELDS\b'), 'M.FIELDS'),
    (re.compile(r'\bMALIK WASHINGTON\b'), 'M.WASHINGTON'),
    (re.compile(r'\bCOREY DYCHES\b'), 'C.DYCHES'),
    (re.compile(r'\bMARCELL OZUNA\b'), 'M.OZUNA'),
    (re.compile(r'\bMATT BREIDA\b'), 'M.BREIDA'),
    (re.compile(r'\bMAX SCHERZER\b'), 'M.SCHERZER'),
    (re.compile(r'\bMILES SANDERS\b'), 'M.SANDERS'),
    (re.compile(r'\bMITCH GARVER\b'), 'M.GARVER'),
    (re.compile(r'\bNATASHA CLOUD\b'), 'N.CLOUD'),
    (re.compile(r'\bNATASHA HOWARD\b'), 'N.HOWARD'),
    (re.compile(r'\bNAJEE HARRIS\b'), 'N.HARRIS'),
    (re.compile(r'\bNOLAN ARENADO\b'), 'N.ARENADO'),
    (re.compile(r'\bPAUL GOLDSCHMIDT\b'), 'P.GOLDSCHMIDT'),
    (re.compile(r'\bPERRIS JONES\b'), 'P.JONES'),
    (re.compile(r'\bRACHAAD WHITE\b'), 'R.WHITE'),
    (re.compile(r'\bRHYNE HOWARD\b'), 'R.HOWARD'),
    (re.compile(r'\bRUSSELL WILSON\b'), 'R.WILSON'),
    (re.compile(r'\bSABRINA IONESCU\b'), 'S.IONESCU'),
    (re.compile(r'\bSAM HOWELL\b'), 'S.HOWELL'),
    (re.compile(r'\bSATOU SABALLY\b'), 'S.SABALLY'),
    (re.compile(r'\bSPENCER HORWITZ\b'), 'S.HORWITZ'),
    (re.compile(r'\S.HALLER\b'), 'S.HALLER'),
    (re.compile(r'\bSAQUON BARKLEY\b'), 'S.BARKLEY'),
    (re.compile(r'\bSTEFON DIGGS\b'), 'S.DIGGS'),
    (re.compile(r'\bTAULIA TAGOVAILOA\b'), 'T.TAGOVAILOA'),
    (re.compile(r'\bTERRELL VAUGHN\b'), 'T.VAUGHN'),
    (re.compile(r'\bT\.ETIENNE JR\.\b'), 'T.ETIENNE'),
    (re.compile(r'\bTREA TURNER\b'), 'T.TURNER'),
    (re.compile(r'\bTYLER LOCKETT\b'), 'T.LOCKETT'),
    (re.compile(r'\bTYLER HIGBEE\b'), 'T.HIGBEE'),
    (re.compile(r'\bTYREEK HILL\b'), 'T.HILL'),
    (re.compile(r'\bTYRONE TAYLOR\b'), 'T.TAYLOR'),
    (re.compile(r'\bWILLIAM CONTRERAS\b'), 'W.CONTRERAS'),
    (re.compile(r'\bWILLY ADAMES\b'), 'W.ADAMES'),
    (re.compile(r'\bYORDAN ALVAREZ\b'), 'Y.ALVAREZ'),
    (re.compile(r'\bZACH WILSON\b'), 'Z.WILSON '),
    (re.compile(r'\bZAC GALLEN\b'), 'Z.GALLEN '),

    #NBA PLAYERS
    (re.compile(r'\bGIANNIS ANTETOKOUNMPO\b'), 'G.ANTETOKOUNMPO'),
    (re.compile(r'\bDEVIN BOOKER\b'), 'D.BOOKER'),
    (re.compile(r'\bLUKA DONCIC\b'), 'L.DONCIC'),
    (re.compile(r'\bJAYSON TATUM\b'), 'J.TATUM'),
    (re.compile(r'\bTYRESE HALIBURTON\b'), 'T.HALIBURTON'),
    (re.compile(r'\bSHAI GILGEOUS-ALEXANDER\b'), 'S.GILGEOUS'),
    (re.compile(r'\bKAWHI LEONARD\b'), 'K.LEONARD'),
    (re.compile(r'\bPAOLO BANCHERO\b'), 'P.BANCHERO'),
    (re.compile(r'\bSTEPHEN CURRY\b'), 'S.CURRY'),
    (re.compile(r'\bTRAE YOUNG\b'), 'T.YOUNG'),

]

# List of patterns to ignore
ignore_patterns = [
    re.compile(r'-LOGO', re.IGNORECASE),  # Case-insensitive match for "-logo"
    re.compile(r'\bAT\b', re.IGNORECASE),  # Case-insensitive match for the word "TODAY"
    re.compile(r'\bTODAY\b', re.IGNORECASE),  # Case-insensitive match for the word "TODAY"
    re.compile(r'\bTOMORROW\b', re.IGNORECASE),  # Case-insensitive match for the word "TODAY"
]
