import re
import tkinter as tk
from tkinter import simpledialog

# Your existing exclusion and replacement patterns
exclude_patterns = [
    re.compile(r'^\s*\+'),
    re.compile(r'^\s*-\s*'),
    re.compile(r'^\s*YES'),
    re.compile(r'^\s*1st Touchdown Scorer / 2nd Touchdown Scorer'),
    re.compile(r'^\s*BOOSTED ODDS'),
    re.compile(r'^\s*SPECIALS'),
    re.compile(r'^\s*BOOSTED WIN PARLAY'),
    re.compile(r'^\s*ODDS BOOST - BOOSTED WIN PARLAY'),
    re.compile(r'^\s*ODDS BOOST - ODDS BOOST'),
    re.compile(r'^\s*ODDS BOOST'),
    re.compile(r'^\s*BET BUILDER'),
    re.compile(r'^\s*WINNER'),
    re.compile(r'^\s*REGULAR TIME ONLY'),
    re.compile(r'^\s*#BETYOURWAY - TEAM FOCUS'),
    re.compile(r'^\s*#BETYOURWAY UP TO 10.0'),
    re.compile(r'^\s*#BETYOURWAY UP TO 26.0'),
    re.compile(r'^\s*PARLAYS: ODDS < \+1000'),
    re.compile(r'^\s*PARLAYS: ODDS > \+5000'),
    re.compile(r'^\s*PARLAYS: ODDS \+\d+ TO \+\d+'),
    re.compile(r'^\s*PERFORMANCE DOUBLES'),
    re.compile(r'^\s*REQUESTED SPECIALS'),
    re.compile(r'^\s*REGULAR TIME ONLY. BETS SETTLED USING OPTA DATA. THE PLAYERS MUST START THE MATCH FOR BETS TO STAND.'),
    re.compile(r'^\s*BETS SETTLED USING OPTA DATA. THE PLAYER MUST START THE MATCH FOR BETS TO STAND.'),
    re.compile(r'^\s*BETS SETTLED USING OPTA DATA. THE PLAYERS MUST START THE MATCH FOR BETS TO STAND.'),
    re.compile(r'^\s*THE PLAYER MUST START THE MATCH FOR BETS TO STAND'),
    re.compile(r'^\s*THE PLAYERS MUST START THE MATCH FOR BETS TO STAND'),
    re.compile(r'^\s*PASS TDS WILL BE CREDITED TO THE RECEIVER NOT THE PASSER FOR WAGERING PURPOSES. OTHERS ON REQUEST.'),
    # Add more patterns here
]


replace_patterns = [
    # Add more REGULAR EXPRESSIONS patterns here
    (re.compile(r'\b -\b'), '-'),
    (re.compile(r'\b \(WAS\)\b'), '(WAS)'),
    (re.compile(r'\b \(\b'), '('),
    (re.compile(r'\b\)\s{2},\b'), '),'),
    (re.compile(r'\b / \b'), '/'),
    (re.compile(r'\b AND \b'), '/'),
    (re.compile(r'\bSHOTS ON GOAL\b'), 'SOT'),
    (re.compile(r'\bTO COMBINE FOR \b'), 'COMBINED'),
    (re.compile(r'\bTO HAVE \b'), ''),
    (re.compile(r'\bTO SCORE THE 1ST TOUCHDOWN OF THE MATCH\b'), 'SCORE 1ST TD IN GAME'),
    (re.compile(r'\bTO SCORE\b'), 'SCORE'),
    (re.compile(r'\bTO WIN\b'), 'WINS'),
    (re.compile(r'\b\ & \b'), '/'),
    (re.compile(r'\b\) \& \b'), '),'),
    (re.compile(r'\b\) \, \b'), '),'),
    (re.compile(r'\b\+ \b'), '+'),
    (re.compile(r'\b, \b'), ','),
    (re.compile(r'\b ,\b'), ','),
    (re.compile(r'\b , \b'), ','),


    # Add more TEAMS replacement patterns here
    (re.compile(r'\bSTATE\b'), 'ST'),
    (re.compile(r'\bARI CARDINALS\b'), 'CARDINALS'),
    (re.compile(r'\bARIZONA CARDINALS\b'), 'ARI CARDINALS'),
    (re.compile(r'\bCAR PANTHERS\b'), 'PANTHERS'),
    (re.compile(r'\bCAROLINA PANTHERS\b'), 'CAR PANTHERS'),
    (re.compile(r'\bMIN VIKINGS\b'), 'VIKINGS'),
    (re.compile(r'\bMINNESOTA VIKINGS\b'), 'VIKINGS'),
    (re.compile(r'\bNY GIANTS\b'), 'GIANTS'),
    (re.compile(r'\bNEW YORK GIANTS\b'), 'NY GIANTS'),
    (re.compile(r'\bPHI EAGLES\b'), 'EAGLES'),
    (re.compile(r'\bPHILADELPHIA EAGLES\b'), 'PHI EAGLES'),
    (re.compile(r'\bSEA SEAHAWKS\b'), 'SEAHAWKS'),
    (re.compile(r'\bSEATTLE SEAHAWKS\b'), 'SEA SEAHAWKS'),
    (re.compile(r'\bTEN TITANS\b'), 'TITANS'),
    (re.compile(r'\bTENNESSEE TITANS\b'), 'TEN TITANS'),
    (re.compile(r'\bWAS COMMANDERS\b'), 'COMMANDERS'),
    (re.compile(r'\bWASHINGTON COMMANDERS\b'), 'WAS COMMANDERS'),



    # Add more NHL TEAMS replacement patterns here
    (re.compile(r'\bCBJ\b'), 'CLB BLUE JACKETS'),
    (re.compile(r'\bCOLUMBUS BLUE JACKETS\b'), 'CLB BLUE JACKETS'),
    (re.compile(r'\bMTL\b'), 'MON CANADIENS'),
    (re.compile(r'\bMONTREAL CANADIENS\b'), 'MON CANADIENS'),
    (re.compile(r'\bNYR\b'), 'NY RANGERS'),
    (re.compile(r'\bNEW YORK RANGERS\b'), 'NY RANGERS'),
    (re.compile(r'\bDET\b'), 'DET RED WINGS'),
    (re.compile(r'\bDETROIT RED WINGS\b'), 'DET RED WINGS'),
    (re.compile(r'\bLA\b'), 'LA KINGS'),
    (re.compile(r'\bLOS ANGELES KINGS\b'), 'LA KINGS'),
    (re.compile(r'\bWSH\b'), 'WAS CAPITALS'),
    (re.compile(r'\bWASHINGTON CAPITALS\b'), 'WAS CAPITALS'),
    (re.compile(r'\bCHI\b'), 'CHI BLACKHAWKS'),
    (re.compile(r'\bCHICAGO BLACKHAWKS\b'), 'CHI BLACKHAWKS'),
    (re.compile(r'\bBOS\b'), 'BOS BRUINS'),
    (re.compile(r'\bBOSTON BRUINS\b'), 'BOS BRUINS'),
    (re.compile(r'\bSJ\b'), 'SJ SHARKS'),
    (re.compile(r'\bSAN JOSE SHARKS\b'), 'SJ SHARKS'),
    (re.compile(r'\bSEA\b'), 'SEA KRAKEN'),
    (re.compile(r'\bSEATTLE KRAKEN\b'), 'SEA KRAKEN'),
    (re.compile(r'\bTOR\b'), 'TOR MAPLE LEAFS'),
    (re.compile(r'\bTORONTO MAPLE LEAFS\b'), 'TOR MAPLE LEAFS'),
    (re.compile(r'\bPHI\b'), 'PHI FLYERS'),
    (re.compile(r'\bPHILADELPHIA FLYERS\b'), 'PHI FLYERS'),
    (re.compile(r'\bNJ\b'), 'NJ DEVILS'),
    (re.compile(r'\bNEW JERSEY DEVILS\b'), 'NJ DEVILS'),
    (re.compile(r'\bPIT\b'), 'PIT PENGUINS'),
    (re.compile(r'\bPITTSBURGH PENGUINS\b'), 'PIT PENGUINS'),
    (re.compile(r'\bTB\b'), 'TB LIGHTNING'),
    (re.compile(r'\bTAMPA BAY LIGHTNING\b'), 'TB LIGHTNING'),
    (re.compile(r'\bFLA\b'), 'FLA PANTHERS'),
    (re.compile(r'\bFLORIDA PANTHERS\b'), 'FLA PANTHERS'),
    (re.compile(r'\bNYI\b'), 'NY ISLANDERS'),
    (re.compile(r'\bNEW YORK ISLANDERS\b'), 'NY ISLANDERS'),
    (re.compile(r'\bCAR\b'), 'CAR HURRICANES'),
    (re.compile(r'\bCAROLINA HURRICANES\b'), 'CAR HURRICANES'),
    (re.compile(r'\bBUF\b'), 'BUF SABRES'),
    (re.compile(r'\bBUFFALO SABRES\b'), 'BUF SABRES'),
    (re.compile(r'\bSTL\b'), 'STL BLUES'),
    (re.compile(r'\bST. LOUIS BLUES\b'), 'STL BLUES'),
    (re.compile(r'\bEDM\b'), 'EDM OILERS'),
    (re.compile(r'\bEDMONTON OILERS\b'), 'EDM OILERS'),
    (re.compile(r'\bWPG\b'), 'WIN JETS'),
    (re.compile(r'\bWINNIPEG JETS\b'), 'WIN JETS'),
    (re.compile(r'\bMIN\b'), 'MIN WILD'),
    (re.compile(r'\bMINNESOTA WILD\b'), 'MIN WILD'),
    (re.compile(r'\bNSH\b'), 'NAS PREDATORS'),
    (re.compile(r'\bNASHVILLE PREDATORS\b'), 'NAS PREDATORS'),
    (re.compile(r'\bDAL\b'), 'DAL STARS'),
    (re.compile(r'\bDALLAS STARS\b'), 'DAL STARS'),
    (re.compile(r'\bCGY\b'), 'CAL FLAMES'),
    (re.compile(r'\bCALGARY FLAMES\b'), 'CAL FLAMES'),
    (re.compile(r'\bCOL\b'), 'COL AVALANCHE'),
    (re.compile(r'\bCOLORADO AVALANCHE\b'), 'COL AVALANCHE'),
    (re.compile(r'\bARI\b'), 'ARZ COYOTES'),
    (re.compile(r'\bARIZONA COYOTES\b'), 'ARZ COYOTES'),
    (re.compile(r'\bANA\b'), 'ANA DUCKS'),
    (re.compile(r'\bANAHEIM DUCKS\b'), 'ANA DUCKS'),
    (re.compile(r'\bVGK\b'), 'VGS GOLDEN KNIGHTS'),
    (re.compile(r'\bVEGAS GOLDEN KNIGHTS\b'), 'VGS GOLDEN KNIGHTS'),
    (re.compile(r'\bVAN\b'), 'VAN CANUCKS'),
    (re.compile(r'\bVANCOUVER CANUCKS\b'), 'VAN CANUCKS'),
    (re.compile(r'\bOTT\b'), 'OTT SENATORS'),
    (re.compile(r'\bOTTAWA SENATOR\b'), 'OTT SENATORS'),


    # Add more NBA TEAMS replacement patterns here
    (re.compile(r'\bORLANDO MAGIC\b'), 'ORL MAGIC'),
    (re.compile(r'\bWASHINGTON WIZARDS\b'), 'WAS WIZARDS'),
    (re.compile(r'\bDETROIT PISTONS\b'), 'DET PISTONS'),
    (re.compile(r'\bTORONTO RAPTORS\b'), 'TOR RAPTORS'),
    (re.compile(r'\bPHOENIX SUNS\b'), 'PHX SUNS'),
    (re.compile(r'\bNEW ORLEANS PELICANS\b'), 'NO PELICANS'),
    (re.compile(r'\bPHILADELPHIA 76ERS\b'), 'PHI 76ERS'),
    (re.compile(r'\bMEMPHIS GRIZZLIES\b'), 'MEM GRIZZLIES'),
    (re.compile(r'\bUTAH JAZZ\b'), 'UTA JAZZ'),
    (re.compile(r'\bDENVER NUGGETS\b'), 'DEN NUGGETS'),
    (re.compile(r'\bHOUSTON ROCKETS\b'), 'HOU ROCKETS'),
    (re.compile(r'\bSACRAMENTO KINGS\b'), 'SAC KINGS'),
    (re.compile(r'\bBROOKLYN NETS\b'), 'BKN NETS'),
    (re.compile(r'\bCHARLOTTE HORNETS\b'), 'CHA HORNETS'),
    (re.compile(r'\bCLEVELAND CAVALIERS\b'), 'CLE CAVALIERS'),
    (re.compile(r'\bPORTLAND TRAIL BLAZERS\b'), 'POR TRAIL BLAZERS'),
    (re.compile(r'\bNEW YORK KNICKS\b'), 'NY KNICKS'),
    (re.compile(r'\bINDIANA PACERS\b'), 'IND PACERS'),
    (re.compile(r'\bMIAMI HEAT\b'), 'MIA HEAT'),
    (re.compile(r'\bMINNESOTA TIMBERWOLVES\b'), 'MIN TIMBERWOLVES'),
    (re.compile(r'\bMILWAUKEE BUCKS\b'), 'MIL BUCKS'),
    (re.compile(r'\bATLANTA HAWKS\b'), 'ATL HAWKS'),
    (re.compile(r'\bSAN ANTONIO SPURS\b'), 'SA SPURS'),
    (re.compile(r'\bOKLAHOMA CITY THUNDER\b'), 'OKC THUNDER'),
    (re.compile(r'\bCHICAGO BULLS\b'), 'CHI BULLS'),
    (re.compile(r'\bGOLDEN STATE WARRIORS\b'), 'GS WARRIORS'),
    (re.compile(r'\bBOSTON CELTICS\b'), 'BOS CELTICS'),
    (re.compile(r'\bDALLAS MAVERICKS\b'), 'DAL MAVERICKS'),
    (re.compile(r'\bLOS ANGELES CLIPPERS\b'), 'LA CLIPPERS'),
    (re.compile(r'\bGOLDEN ST WARRIORS\b'), 'GS WARRIORS'),



    # Add more TEAMS replacement patterns here
    (re.compile(r'\bATLANTA DREAM\b'), 'ATL DREAM'),
    (re.compile(r'\bDALLAS WINGS\b'), 'DAL WINGS'),
    (re.compile(r'\bNEW YORK LIBERTY\b'), 'NY LIBERTY'),
    (re.compile(r'\bWASHINGTON MYSTICS\b'), 'WAS MYSTICS'),

    # Add more BASKETBALL patterns here
    (re.compile(r'\bTOTAL POINTS OVER\b'), 'TOT PTS OV'),
    (re.compile(r'\bTOTAL POINTS UNDER\b'), 'TOT PTS UND'),
    (re.compile(r'\bTHREE POINT FIELD GOALS\b'), '3PT FG MADE'),
    (re.compile(r'\bREBOUNDS\b'), 'RBDS'),
    (re.compile(r'\bASSISTS\b'), 'ASSTS'),
    (re.compile(r'\bPOINTS\b'), 'PTS'),
    (re.compile(r'\bTOTAL\b'), 'TOT'),

    # Add more BASEBALL replacement patterns here

    (re.compile(r'\bHOME RUNS\b'), 'HRS'),
    (re.compile(r'\bSTRIKEOUTS \b'), 'SO'),
    (re.compile(r'\bSTRIKEOUTS/\b'), 'SO/'),
    (re.compile(r'\bSTRIKEOUTS\b'), 'SO'),

    # Add more SOCCER patterns here
    (re.compile(r'\bSHOTS ON GOAL\b'), 'SOT'),

    # Add more FOOTBALL patterns here
    (re.compile(r'\b1ST QUARTER\b'), '1Q'),
    (re.compile(r'\bANYTIME TOUCHDOWN EACH\b'), 'TD EACH'),
    (re.compile(r'\b PASSING YARDS\b'), 'PASS YDS'),
    (re.compile(r'\b RECEIVING YARDS\b'), 'RCV YDS'),
    (re.compile(r'\bREC\. YARDS\b'), 'RCV YDS'),
    (re.compile(r'\b RUSHING YARDS\b'), 'RUSH YDS'),
    (re.compile(r'\bANYTIME TOUCHDOWN EACH\b'), 'TD EACH'),
    (re.compile(r'\bCARRIES\b'), 'CAR'),
    (re.compile(r'\bCOMPLETIONS\b'), 'CMPTS'),
    (re.compile(r'\bPASSING TDS\b'), 'PASS TDS'),
    (re.compile(r'\bPASSING TOUCHDOWNS\b'), 'PASS TDS'),
    (re.compile(r'\bPASSING YARDS\b'), 'PASS YDS'),
    (re.compile(r'\bPASSING YDS\b'), 'PASS YDS'),
    (re.compile(r'\bPASSING\b'), 'PASS'),
    (re.compile(r'\bRECEIVING YARDS\b'), 'RCV YDS'),
    (re.compile(r'\bRECEPTIONS\b'), 'RCPTS'),
    (re.compile(r'\bRUSHING YARDS\b'), 'RUSH YDS'),
    (re.compile(r'\bRUSHING YDS\b'), 'RUSH YDS'),
    (re.compile(r'\bRUSHING\b'), 'RUSH'),
    (re.compile(r'\bRUSH TOUCHDOWN\b'), 'RUSH TDS'),
    (re.compile(r'\bTOUCHDOWNS\b'), 'TDS'),
    (re.compile(r'\bA TOUCHDOWN\b'), 'A TD'),
    (re.compile(r'\bYARDS\b'), 'YDS'),

    # Add more PLAYER NAMES patterns here
    (re.compile(r'\bAMON-RA ST\. BROWN\b'), 'AMON ST BROWN'),
    (re.compile(r'\bADRIAN HOUSER\b'), 'A.HOUSER'),
    (re.compile(r'\bAARON JONES\b'), 'A.JONES'),
    (re.compile(r'\bAARON JUDGE\b'), 'A.JUDGE'),
    (re.compile(r'\bAARON NOLA\b'), 'A.NOLA'),
    (re.compile(r'\bAARON RODGERS\b'), 'A.RODGERS'),
    (re.compile(r'\bANTHONY RICHARDSON\b'), 'A.RICHARDSON'),
    (re.compile(r'\bALBERT OKWUEGBUNAM\b'), 'A.OKWUEGBUNAM'),
    (re.compile(r'\bALEXANDER MATTISON\b'), 'A.MATTISON'),
    (re.compile(r'\bALLEN ROBINSON\b'), 'A.ROBINSON'),
    (re.compile(r'\bALLISHA GRAY\b'), 'A.GRAY'),
    (re.compile(r'\bALVARO MORATA\b'), 'A.MORATA'),
    (re.compile(r'\bANDREA BELOTTI\b'), 'A.BELOTTI'),
    (re.compile(r'\bANTHONY MCFARLAND\b'), 'A.MCFARLAND'),
    (re.compile(r'\bARIKE OGUNBOWALE\b'), 'A.OGUNBOWALE'),
    (re.compile(r'\bBAKER MAYFIELD\b'), 'B.MAYFIELD'),
    (re.compile(r'\bBIJAN ROBINSON\b'), 'B.ROBINSON'),
    (re.compile(r'\bBRANDON AIYUK\b'), 'B.AIYUK'),
    (re.compile(r'\bBRAXTON GARRETT\b'), 'B.GARRETT'),
    (re.compile(r'\bBREECE HALL\b'), 'B.HALL'),
    (re.compile(r'\bBRIAN ROBINSON\b'), 'B.ROBINSON'),
    (re.compile(r'\bBROCK PURDY\b'), 'B.PURDY'),
    (re.compile(r'\bCALVIN AUSTIN\b'), 'C.AUSTIN'),
    (re.compile(r'\bCHEYENNE PARKER\b'), 'C.PARKER'),
    (re.compile(r'\bCHRIS GODWIN\b'), 'C.GODWIN'),
    (re.compile(r'\bCHRIS OLAVE\b'), 'C.OLAVE'),
    (re.compile(r'\bCHRIS RODRIGUEZ\b'), 'C.RODRIGUEZ'),
    (re.compile(r'\bCHRISTIAN MCCAFFREY\b'), 'C.MCCAFFREY'),
    (re.compile(r'\bCHRISTIAN KIRK\b'), 'C.KIRK'),
    (re.compile(r'\bCHRISTIAN WATSON\b'), 'C.WATSON'),
    (re.compile(r'\bCIRO IMMOBILE\b'), 'C.IMMOBILE'),
    (re.compile(r'\bCALVIN RIDLEY\b'), 'C.RIDLEY'),
    (re.compile(r'\bCEEDEE LAMB\b'), 'C.LAMB'),
    (re.compile(r'\bCOLBY PARKINSON\b'), 'C.PARKINSON'),
    (re.compile(r'\bCOOPER LEGAS \b'), 'C.LEGAS '),
    (re.compile(r'\bCORDARRELLE PATTERSON\b'), 'C.PATTERSON'),
    (re.compile(r'\bCOURTLAND SUTTON\b'), 'C.SUTTON'),
    (re.compile(r'\bDAVID MONTGOMERY\b'), 'D.MONTGOMERY'),
    (re.compile(r'\bDARNELL WASHINGTON\b'), 'D.WASHINGTON'),
    (re.compile(r'\bDAK PRESCOTT\b'), 'D.PRESCOTT'),
    (re.compile(r'\bDAVANTE ADAMS\b'), 'D.ADAMS'),
    (re.compile(r'\bPAULO DYBALA\b'), 'P.DYBALA'),
    (re.compile(r'\bABOU OUATTARA\b'), 'A.OUATTARA'),
    (re.compile(r'\bSTEVEN BERGWIJN\b'), 'S.BERGWIJN'),
    (re.compile(r'\bBRIAN BROBBEY\b'), 'B.BROBBEY'),
    (re.compile(r'\bAMINE HARIT\b'), 'A.HARIT'),
    (re.compile(r'\bDANIEL JONES\b'), 'D.JONES'),
    (re.compile(r'\bDAULTON VARSHO\b'), 'D.VARSHO'),
    (re.compile(r'\bDEANDRE HOPKINS\b'), 'D.HOPKINS'),
    (re.compile(r'\bDEMARIO DOUGLAS\b'), 'D.DOUGLAS'),
    (re.compile(r'\bDENIS BOUANGA\b'), 'D.BOUANGA'),
    (re.compile(r'\bDEONTE HARTY\b'), 'D.HARTY'),
    (re.compile(r'\bDEREK CARR\b'), 'D.CARR'),
    (re.compile(r'\bDESHAUN WATSON\b'), 'D.WATSON'),
    (re.compile(r'\bDESMOND RIDDER\b'), 'D.RIDDER'),
    (re.compile(r'\bDEVONTA SMITH\b'), 'D.SMITH'),
    (re.compile(r'\bDONALD PARHAM\b'), 'D.PARHAM'),
    (re.compile(r'\bDONOVAN PEOPLES-JONES\b'), 'D.PEOPLES-JONES'),
    (re.compile(r'\bDRAKE LONDON\b'), 'D.LONDON'),
    (re.compile(r'\bEMMANUEL MICHEL\b'), 'E.MICHEL'),
    (re.compile(r'\bELENA DELLE DONNE\b'), 'E.DONNE'),
    (re.compile(r'\bELIJAH MOORE\b'), 'E.MOORE'),
    (re.compile(r'\bEQUANIMEOUS ST. BROWN\b'), 'E.ST. BROWN'),
    (re.compile(r'\bERLING HAALAND\b'), 'E.HAALAND'),
    (re.compile(r'\bFOSTER MOREAU\b'), 'F.MOREAU'),
    (re.compile(r'\bGARRETT WILSON\b'), 'G.WILSON'),
    (re.compile(r'\bGENO SMITH\b'), 'G.SMITH'),
    (re.compile(r'\bGRANT CALCATERRA\b'), 'G.CALCATERRA'),
    (re.compile(r'\bGLEYBER TORRES\b'), 'G.TORRES'),
    (re.compile(r'\bGUNNER OLSZEWSKI\b'), 'G.OLSZEWSKI'),
    (re.compile(r'\bIHMIR SMITH-MARSETTE\b'), 'I.SMITH-MARSETTE'),
    (re.compile(r'\bISIAH PACHECO\b'), 'I.PACHECO'),
    (re.compile(r'\bJAHMYR GIBBS\b'), 'J.GIBBS'),
    (re.compile(r'\bJALEEL MCLAUGHLIN\b'), 'J.MCLAUGHLIN'),
    (re.compile(r'\bJALEN HURTS\b'), 'J.HURTS'),
    (re.compile(r'\bJAMAAL WILLIAMS\b'), 'J.WILLIAMS'),
    (re.compile(r'\bJA\'MARR CHASE\b'), 'J.CHASE'),
    (re.compile(r'\bJARED GOFF\b'), 'J.GOFF'),
    (re.compile(r'\bJAVONTE WILLIAMS\b'), 'J.WILLIAMS'),
    (re.compile(r'\bJESHAUN JONES\b'), 'J.JONES'),
    (re.compile(r'\bJIMMY GAROPPOLO\b'), 'J.GAROPPOLO'),
    (re.compile(r'\bJOE BURROW\b'), 'J.BURROW'),
    (re.compile(r'\bJOHN LEE ELDRIDGE III\b'), 'J.ELDRIDGE III'),
    (re.compile(r'\bJORDAN LOVE\b'), 'J.LOVE'),
    (re.compile(r'\bJUJU SMITH-SCHUSTER\b'), 'SMITH-SCHUSTER'),
    (re.compile(r'\bJULIAN ALVAREZ\b'), 'J.ALVAREZ'),
    (re.compile(r'\bJUSTIN HERBERT\b'), 'J.HERBERT'),
    (re.compile(r'\bJUSTIN JEFFERSON\b'), 'J.JEFFERSON'),
    (re.compile(r'\bKYLIAN MBAPPE\b'), 'K.MBAPPE'),
    (re.compile(r'\bKADEN PRATHER\b'), 'K.PRATHER'),
    (re.compile(r'\bKENNETH GAINWELL\b'), 'K.GAINWELL'),
    (re.compile(r'\bKENNETH WALKER III\b'), 'K.WALKER III'),
    (re.compile(r'\bKENDRE MILLER\b'), 'K.MILLER'),
    (re.compile(r'\bKENNY PICKETT\b'), 'K.PICKETT'),
    (re.compile(r'\bKEVIN GAUSMAN\b'), 'K.GAUSMAN'),
    (re.compile(r'\bKHVICHA KVARATSKHELIA\b'), 'K.KVARATSKHELIA '),
    (re.compile(r'\bKIRK COUSINS\b'), 'K.COUSINS'),
    (re.compile(r'\bKRISTIAN WILKERSON\b'), 'K.WILKERSON'),
    (re.compile(r'\bKYLE PITTS\b'), 'K.PITTS'),
    (re.compile(r'\bKYLEN GRANSON\b'), 'K.GRANSON'),
    (re.compile(r'\bLAMAR JACKSON\b'), 'L.JACKSON'),
    (re.compile(r'\bLAVISKA SHENAULT JR\b'), 'L.SHENAULT JR'),
    (re.compile(r'\bLAVISKA SHENAULT\b'), 'L.SHENAULT'),
    (re.compile(r'\bLEONARDO CAMPANA\b'), 'L.CAMPANA'),
    (re.compile(r'\bLOIS OPENDA\b'), 'L.OPENDA'),
    (re.compile(r'\bLORENZO INSIGNE\b'), 'L.INSIGNE'),
    (re.compile(r'\bMALACHI FIELDS\b'), 'M.FIELDS'),
    (re.compile(r'\bMALIK WASHINGTON\b'), 'M.WASHINGTON'),
    (re.compile(r'\bCOREY DYCHES\b'), 'C.DYCHES'),
    (re.compile(r'\bMAC JONES\b'), 'M.JONES'),
    (re.compile(r'\bMACK HOLLINS\b'), 'M.HOLLINS'),
    (re.compile(r'\bMARQUEZ VALDES-SCANTLING\b'), 'M.VALDES-SCANTLING'),
    (re.compile(r'\bMATT BREIDA\b'), 'M.BREIDA'),
    (re.compile(r'\bMATTHEW STAFFORD\b'), 'M.STAFFORD'),
    (re.compile(r'\bMICHAEL PITTMAN\b'), 'M.PITTMAN'),
    (re.compile(r'\bMICHAEL THOMAS\b'), 'M.THOMAS'),
    (re.compile(r'\bMILES SANDERS\b'), 'M.SANDERS'),
    (re.compile(r'\bNATASHA CLOUD\b'), 'N.CLOUD'),
    (re.compile(r'\bNATASHA HOWARD\b'), 'N.HOWARD'),
    (re.compile(r'\bNAJEE HARRIS\b'), 'N.HARRIS'),
    (re.compile(r'\bNICK CASTELLANOS\b'), 'N.CASTELLANOS'),
    (re.compile(r'\bNICK WESTBROOK-IKHINE\b'), 'N.WESTBROOK-IKHINE'),
    (re.compile(r'\bNICK WESTBROOK-IKHINE\b'), 'WESTBROOK-IKHINE'),
    (re.compile(r'\bNOLAN ARENADO\b'), 'N.ARENADO'),
    (re.compile(r'\bODELL BECKHAM JR\b'), 'O.BECKHAM JR'),
    (re.compile(r'\bOLAMIDE ZACCHEAUS\b'), 'O.ZACCHEAUS'),
    (re.compile(r'\bPARKER WASHINGTON\b'), 'P.WASHINGTON'),
    (re.compile(r'\bPATRICK MAHOMES\b'), 'P.MAHOMES'),
    (re.compile(r'\bPAUL GOLDSCHMIDT\b'), 'P.GOLDSCHMIDT'),
    (re.compile(r'\bPEYTON HENDERSHOT\b'), 'P.HENDERSHOT'),
    (re.compile(r'\bPERRIS JONES\b'), 'P.JONES'),
    (re.compile(r'\bRACHAAD WHITE\b'), 'R.WHITE'),
    (re.compile(r'\bRAHEEM BLACKSHEAR\b'), 'R.BLACKSHEAR'),
    (re.compile(r'\bRHAMONDRE STEVENSON\b'), 'R.STEVENSON'),
    (re.compile(r'\bRHYNE HOWARD\b'), 'R.HOWARD'),
    (re.compile(r'\bRYAN TANNEHILL\b'), 'R.TANNEHILL'),
    (re.compile(r'\bRUSSELL WILSON\b'), 'R.WILSON'),
    (re.compile(r'\bSABRINA IONESCU\b'), 'S.IONESCU'),
    (re.compile(r'\bSAM HOWELL\b'), 'S.HOWELL'),
    (re.compile(r'\bSATOU SABALLY\b'), 'S.SABALLY'),
    (re.compile(r'\bSPENCER HORWITZ\b'), 'S.HORWITZ'),
    (re.compile(r'\S.HALLER\b'), 'S.HALLER'),
    (re.compile(r'\bSTEFON DIGGS\b'), 'S.DIGGS'),
    (re.compile(r'\bSTEPHAN EL SHAARAWY\b'), 'S.EL SHAARAWY'),
    (re.compile(r'\bTAULIA TAGOVAILOA\b'), 'T.TAGOVAILOA'),
    (re.compile(r'\bTERRACE MARSHALL JR\b'), 'T.MARSHALL JR'),
    (re.compile(r'\bTERRELL VAUGHN\b'), 'T.VAUGHN'),
    (re.compile(r'\bTIMO WERNER\b'), 'T.WERNER'),
    (re.compile(r'\bT\.ETIENNE JR\.\b'), 'T.ETIENNE'),
    (re.compile(r'\bTRAVIS ETIENNE\b'), 'T.ETIENNE'),
    (re.compile(r'\bTRAVIS KELCE\b'), 'T.KELCE'),
    (re.compile(r'\bTRAYVEON WILLIAMS\b'), 'T.WILLIAMS'),
    (re.compile(r'\bTREA TURNER\b'), 'T.TURNER'),
    (re.compile(r'\bTYLER LOCKETT\b'), 'T.LOCKETT'),
    (re.compile(r'\bTYLER HIGBEE\b'), 'T.HIGBEE'),
    (re.compile(r'\bTYRONE TAYLOR\b'), 'T.TAYLOR'),
    (re.compile(r'\bTUA TAGOVAILOA\b'), 'T.TAGOVAILOA'),
    (re.compile(r'\bTONY POLLARD\b'), 'T.POLLARD'),
    (re.compile(r'\bVICTOR OSIMHEN\b'), 'V.OSIMHEN'),
    (re.compile(r'\bVINICIUS JUNIOR\b'), 'V.JUNIOR'),
    (re.compile(r'\bWILLIAM CONTRERAS\b'), 'W.CONTRERAS'),
    (re.compile(r'\bZAY FLOWERS\b'), 'Z.FLOWERS'),
    (re.compile(r'\bZACH WILSON \b'), 'Z.WILSON '),
]